### PR TITLE
Feat:AdvancedSearch/Fix:Reaction Viewer

### PR DESCRIPTION
**Pull request by 1673beta**
## Checklist
- [ ] Read the [contribution guide](https://github.com/kokonect-link/cherrypick/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Update CHANGELOG_CHERRYPICK.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by penginn-0** [comment]
実績周りやりたいかも

**Comment by penginn-0** [comment]
見た目だけ

**Comment by 1673beta** [comment]
これフォルダの中にトグルスイッチ入れるの？

**Comment by 1673beta** [comment]
消し忘れただけ

**Comment by 1673beta** [comment]
fix #45 #43

**Pull request merged**
